# labels
from tkinter import *
from statsframes3 import *

def statslabels3(stats3cap,x):
	labVoisins = Label(x[1],text="Voisins: Tier: Orphelins:", 
		height=1,width=48, bg='#31859B', fg='white', anchor='w',font=('Verdana', 12, 'bold'))
	labVoisins.place(x=6, y=26)
	
	labStats = Label(x[1],text="Stats for Voisins, Tier, Orphelins, Neighbors, Finalbet, Combo & Magic9", 
		height=1,width=56, bg='#31859B', fg='Yellow', anchor='w',font=('Verdana', 12, 'bold'))
	labStats.place(x=6, y=6)

	labVoisins = Label(x[2],text="Voisins", height=1,width=9, bg='black', fg='white').grid(row=0,column=0, padx=1, pady=1)
	labVoisinsR = Label(x[2],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=1, padx=1, pady=1)

	labTier = Label(x[2],text="Tier", height=1,width=9, bg='black', fg='white').grid(row=0,column=2, padx=1, pady=1)
	labTierR = Label(x[2],text="  ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=3, padx=1, pady=1)

	labOrphelins = Label(x[2],text="Orphelins", height=1,width=9, bg='black', fg='white').grid(row=0,column=4, padx=1, pady=1)
	labOrphelinsR = Label(x[2],text="  ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=5, padx=1, pady=1)

	labNeighbors = Label(x[1],text="Neighbors:", 
		height=1,width=28, bg='#31859B', fg='white', anchor='w',font=('Verdana', 12, 'bold'))
	labNeighbors.place(x=6, y=82)

	labNeighbors_1 = Label(x[3],text="Neigh 1", height=1,width=9, bg='black', fg='white').grid(row=0,column=0, padx=1, pady=1)
	labNeighbors_1R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=1, padx=1, pady=1)
	labNeighbors_2 = Label(x[3],text="Neigh 2", height=1,width=9, bg='black', fg='white').grid(row=0,column=2, padx=1, pady=1)
	labNeighbors_2R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=3, padx=1, pady=1)
	labNeighbors_3 = Label(x[3],text="Neigh 3", height=1,width=9, bg='black', fg='white').grid(row=0,column=4, padx=1, pady=1)
	labNeighbors_3R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=5, padx=1, pady=1)
	labNeighbors_4 = Label(x[3],text="Neigh 4", height=1,width=9, bg='black', fg='white').grid(row=0,column=6, padx=1, pady=1)
	labNeighbors_4R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=7, padx=1, pady=1)
	labNeighbors_5 = Label(x[3],text="Neigh 5", height=1,width=9, bg='black', fg='white').grid(row=0,column=8, padx=1, pady=1)
	labNeighbors_5R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=9, padx=1, pady=1)
	labNeighbors_6 = Label(x[3],text="Neigh 6", height=1,width=9, bg='black', fg='white').grid(row=0,column=10, padx=1, pady=1)
	labNeighbors_6R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=11, padx=1, pady=1)

	labNeighbors_7 = Label(x[3],text="Neigh 7", height=1,width=9, bg='black', fg='white').grid(row=1,column=0, padx=1, pady=1)
	labNeighbors_7R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=1, padx=1, pady=1)
	labNeighbors_8 = Label(x[3],text="Neigh 8", height=1,width=9, bg='black', fg='white').grid(row=1,column=2, padx=1, pady=1)
	labNeighbors_8R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=3, padx=1, pady=1)
	labNeighbors_9 = Label(x[3],text="Neigh 9", height=1,width=9, bg='black', fg='white').grid(row=1,column=4, padx=1, pady=1)
	labNeighbors_9R = Label(x[3],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=5, padx=1, pady=1)
	labNeighbors_10 = Label(x[3],text="Neigh 10", height=1,width=9, bg='black', fg='white').grid(row=1,column=6, padx=1, pady=1)
	labNeighbors_10R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=7, padx=1, pady=1)
	labNeighbors_11 = Label(x[3],text="Neigh 11", height=1,width=9, bg='black', fg='white').grid(row=1,column=8, padx=1, pady=1)
	labNeighbors_11R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=9, padx=1, pady=1)
	labNeighbors_12 = Label(x[3],text="Neigh 12", height=1,width=9, bg='black', fg='white').grid(row=1,column=10, padx=1, pady=1)
	labNeighbors_12R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=11, padx=1, pady=1)

	labNeighbors_13 = Label(x[3],text="Neigh 13", height=1,width=9, bg='black', fg='white').grid(row=2,column=0, padx=1, pady=1)
	labNeighbors_13R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=1, padx=1, pady=1)
	labNeighbors_14 = Label(x[3],text="Neigh 14", height=1,width=9, bg='black', fg='white').grid(row=2,column=2, padx=1, pady=1)
	labNeighbors_14R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=3, padx=1, pady=1)
	labNeighbors_15 = Label(x[3],text="Neigh 15", height=1,width=9, bg='black', fg='white').grid(row=2,column=4, padx=1, pady=1)
	labNeighbors_15R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=5, padx=1, pady=1)
	labNeighbors_16 = Label(x[3],text="Neigh 16", height=1,width=9, bg='black', fg='white').grid(row=2,column=6, padx=1, pady=1)
	labNeighbors_16R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=7, padx=1, pady=1)
	labNeighbors_17 = Label(x[3],text="Neigh 17", height=1,width=9, bg='black', fg='white').grid(row=2,column=8, padx=1, pady=1)
	labNeighbors_17R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=9, padx=1, pady=1)
	labNeighbors_18 = Label(x[3],text="Neigh 18", height=1,width=9, bg='black', fg='white').grid(row=2,column=10, padx=1, pady=1)
	labNeighbors_18R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=2,column=11, padx=1, pady=1)

	labNeighbors_19 = Label(x[3],text="Neigh 19", height=1,width=9, bg='black', fg='white').grid(row=3,column=0, padx=1, pady=1)
	labNeighbors_19R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=1, padx=1, pady=1)
	labNeighbors_20 = Label(x[3],text="Neigh 20", height=1,width=9, bg='black', fg='white').grid(row=3,column=2, padx=1, pady=1)
	labNeighbors_20R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=3, padx=1, pady=1)
	labNeighbors_21 = Label(x[3],text="Neigh 21", height=1,width=9, bg='black', fg='white').grid(row=3,column=4, padx=1, pady=1)
	labNeighbors_21R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=5, padx=1, pady=1)
	labNeighbors_22 = Label(x[3],text="Neigh 22", height=1,width=9, bg='black', fg='white').grid(row=3,column=6, padx=1, pady=1)
	labNeighbors_22R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=7, padx=1, pady=1)
	labNeighbors_23 = Label(x[3],text="Neigh 23", height=1,width=9, bg='black', fg='white').grid(row=3,column=8, padx=1, pady=1)
	labNeighbors_23R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=9, padx=1, pady=1)
	labNeighbors_24 = Label(x[3],text="Neigh 24", height=1,width=9, bg='black', fg='white').grid(row=3,column=10, padx=1, pady=1)
	labNeighbors_24R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=3,column=11, padx=1, pady=1)

	labNeighbors_25 = Label(x[3],text="Neigh 25", height=1,width=9, bg='black', fg='white').grid(row=4,column=0, padx=1, pady=1)
	labNeighbors_25R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=1, padx=1, pady=1)
	labNeighbors_26 = Label(x[3],text="Neigh 26", height=1,width=9, bg='black', fg='white').grid(row=4,column=2, padx=1, pady=1)
	labNeighbors_26R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=3, padx=1, pady=1)
	labNeighbors_27 = Label(x[3],text="Neigh 27", height=1,width=9, bg='black', fg='white').grid(row=4,column=4, padx=1, pady=1)
	labNeighbors_27R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=5, padx=1, pady=1)
	labNeighbors_28 = Label(x[3],text="Neigh 28", height=1,width=9, bg='black', fg='white').grid(row=4,column=6, padx=1, pady=1)
	labNeighbors_28R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=7, padx=1, pady=1)
	labNeighbors_29 = Label(x[3],text="Neigh 29", height=1,width=9, bg='black', fg='white').grid(row=4,column=8, padx=1, pady=1)
	labNeighbors_29R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=9, padx=1, pady=1)
	labNeighbors_30 = Label(x[3],text="Neigh 30", height=1,width=9, bg='black', fg='white').grid(row=4,column=10, padx=1, pady=1)
	labNeighbors_30R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=4,column=11, padx=1, pady=1)

	labNeighbors_31 = Label(x[3],text="Neigh 31", height=1,width=9, bg='black', fg='white').grid(row=5,column=0, padx=1, pady=1)
	labNeighbors_31R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=1, padx=1, pady=1)
	labNeighbors_32 = Label(x[3],text="Neigh 32", height=1,width=9, bg='black', fg='white').grid(row=5,column=2, padx=1, pady=1)
	labNeighbors_32R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=3, padx=1, pady=1)
	labNeighbors_33 = Label(x[3],text="Neigh 33", height=1,width=9, bg='black', fg='white').grid(row=5,column=4, padx=1, pady=1)
	labNeighbors_33R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=5, padx=1, pady=1)
	labNeighbors_34 = Label(x[3],text="Neigh 34", height=1,width=9, bg='black', fg='white').grid(row=5,column=6, padx=1, pady=1)
	labNeighbors_34R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=7, padx=1, pady=1)
	labNeighbors_35 = Label(x[3],text="Neigh 35", height=1,width=9, bg='black', fg='white').grid(row=5,column=8, padx=1, pady=1)
	labNeighbors_35R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=9, padx=1, pady=1)
	labNeighbors_36 = Label(x[3],text="Neigh 36", height=1,width=9, bg='black', fg='white').grid(row=5,column=10, padx=1, pady=1)
	labNeighbors_36R = Label(x[3],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=5,column=11, padx=1, pady=1)

	labFinalbet = Label(x[1],text="Finalbet:", 
		height=1,width=28, bg='#31859B', fg='white', anchor='w',font=('Verdana', 12, 'bold'))
	labFinalbet.place(x=6, y=250)

	labFinalbet_1 = Label(x[4],text="Final 1", height=1,width=9, bg='black', fg='white').grid(row=0,column=0, padx=1, pady=1)
	labFinalbet_1R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=1, padx=1, pady=1)
	labFinalbet_2 = Label(x[4],text="Final 2", height=1,width=9, bg='black', fg='white').grid(row=0,column=2, padx=1, pady=1)
	labFinalbet_2R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=3, padx=1, pady=1)
	labFinalbet_3 = Label(x[4],text="Final 3", height=1,width=9, bg='black', fg='white').grid(row=0,column=4, padx=1, pady=1)
	labFinalbet_3R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=5, padx=1, pady=1)
	labFinalbet_4 = Label(x[4],text="Final 4", height=1,width=9, bg='black', fg='white').grid(row=0,column=6, padx=1, pady=1)
	labFinalbet_4R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=7, padx=1, pady=1)
	labFinalbet_5 = Label(x[4],text="Final 5", height=1,width=9, bg='black', fg='white').grid(row=0,column=8, padx=1, pady=1)
	labFinalbet_5R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=9, padx=1, pady=1)
	labFinalbet_6 = Label(x[4],text="Final 6", height=1,width=9, bg='black', fg='white').grid(row=0,column=10, padx=1, pady=1)
	labFinalbet_6R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=11, padx=1, pady=1)

	labFinalbet_7 = Label(x[4],text="Final 7", height=1,width=9, bg='black', fg='white').grid(row=1,column=0, padx=1, pady=1)
	labFinalbet_7R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=1, padx=1, pady=1)
	labFinalbet_8 = Label(x[4],text="Final 8", height=1,width=9, bg='black', fg='white').grid(row=1,column=2, padx=1, pady=1)
	labFinalbet_8R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=3, padx=1, pady=1)
	labFinalbet_9 = Label(x[4],text="Final 9", height=1,width=9, bg='black', fg='white').grid(row=1,column=4, padx=1, pady=1)
	labFinalbet_9R = Label(x[4],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=5, padx=1, pady=1)

	labCombo = Label(x[1],text="Combo Even Chances:", height=1,width=48, bg='#31859B', fg='white', anchor='w',font=('Verdana', 12, 'bold')).place(x=6, y=334)

	labRed_Odd = Label(x[5],text="Red_Odd", height=1,width=9, bg='black', fg='white').grid(row=0,column=0, padx=1, pady=1)
	labRed_OddR = Label(x[5],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=1, padx=1, pady=1)
	labRed_Even = Label(x[5],text="Red_Even", height=1,width=9, bg='black', fg='white').grid(row=0,column=2, padx=1, pady=1)
	labRed_EvenR = Label(x[5],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=3, padx=1, pady=1)
	labRed_Low = Label(x[5],text="Red_Low", height=1,width=9, bg='black', fg='white').grid(row=0,column=4, padx=1, pady=1)
	labRed_LowR = Label(x[5],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=5, padx=1, pady=1)
	labRed_High = Label(x[5],text="Red_High", height=1,width=9, bg='black', fg='white').grid(row=0,column=6, padx=1, pady=1)
	labRed_HighR = Label(x[5],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=7, padx=1, pady=1)

	labMagic_9 = Label(x[1],text="Magic9 :", height=1,width=48, bg='#31859B', fg='white', anchor='w',font=('Verdana', 12, 'bold')).place(x=6, y=394)

	Magic9_5 = Label(x[6],text="Magic9 5", height=1,width=9, bg='black', fg='white').grid(row=0,column=0, padx=1, pady=1)
	Magic9_5R = Label(x[6],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=1, padx=1, pady=1)
	Magic9_8 = Label(x[6],text="Magic9 8", height=1,width=9, bg='black', fg='white').grid(row=0,column=2, padx=1, pady=1)
	Magic9_8R = Label(x[6],text="	 ", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=3, padx=1, pady=1)
	Magic9_11 = Label(x[6],text="Magic9 11", height=1,width=9, bg='black', fg='white').grid(row=0,column=4, padx=1, pady=1)
	Magic9_11R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=5, padx=1, pady=1)
	Magic9_14 = Label(x[6],text="Magic9 14", height=1,width=9, bg='black', fg='white').grid(row=0,column=6, padx=1, pady=1)
	Magic9_14R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=7, padx=1, pady=1)
	Magic9_17 = Label(x[6],text="Magic9 17", height=1,width=9, bg='black', fg='white').grid(row=0,column=8, padx=1, pady=1)
	Magic9_17R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=9, padx=1, pady=1)
	Magic9_20 = Label(x[6],text="Magic9 20", height=1,width=9, bg='black', fg='white').grid(row=0,column=10, padx=1, pady=1)
	Magic9_20R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=0,column=11, padx=1, pady=1)

	Magic9_23 = Label(x[6],text="Magic9 23", height=1,width=9, bg='black', fg='white').grid(row=1,column=0, padx=1, pady=1)
	Magic9_23R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=1, padx=1, pady=1)
	Magic9_26 = Label(x[6],text="Magic9 26", height=1,width=9, bg='black', fg='white').grid(row=1,column=2, padx=1, pady=1)
	Magic9_26R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=3, padx=1, pady=1)
	Magic9_29 = Label(x[6],text="Magic9 29", height=1,width=9, bg='black', fg='white').grid(row=1,column=4, padx=1, pady=1)
	Magic9_29R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=5, padx=1, pady=1)
	Magic9_32 = Label(x[6],text="Magic9 32", height=1,width=9, bg='black', fg='white').grid(row=1,column=6, padx=1, pady=1)
	Magic9_32R = Label(x[6],text="	", height=1,width=4, bg='#11390F', fg='white').grid(row=1,column=7, padx=1, pady=1)
